<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
        }

        .container {
            width: 80%;
            margin: auto;
        }

        h1,
        h2 {
            text-align: center;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table th,
        table td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        table th {
            background-color: #f4f4f4;
            font-weight: bold;
            text-align: left;
        }

        table td {
            text-align: right;
        }

        table td:first-child {
            text-align: left;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
        }

        .header-section {
            text-align: center;
            margin-bottom: 20px;
        }

        .report-details {
            margin-top: 10px;
            font-size: 14px;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }

        .approval-section {
            margin-top: 30px;
            display: flex;
            justify-content: space-between;
        }

        .approval-section .signature-box {
            width: 45%;
            border-top: 1px solid #000;
            padding-top: 10px;
            text-align: center;
        }

        .approval-section label {
            font-weight: bold;
        }
    </style>
</head>

<body>
    <div class="container">
        <!-- Header Section -->
        <div class="header-section">
            <h1>CTMJ Gases Supply</h1>
            <h2>Daily Sales Report</h2>
            <p><strong>Report Generated By:</strong> {{ auth()->user()->name ?? 'Unknown User' }}</p>
        </div>

        <!-- Report Table -->
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Total Order</th>
                    <th>Unit Price</th>
                    <th>Total Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($productSalesData as $product)
                    <tr>
                        <td>{{ $product->product_name }}</td>
                        <td>{{ $product->total_quantity }}</td>
                        <td>{{ number_format($product->unit_price, 2) }}</td>
                        <td>{{ number_format($product->total_price, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" style="text-align: right; font-weight: bold;">Total Amount:</td>
                    <td style="font-weight: bold;">
                        {{ number_format($productSalesData->sum('total_price'), 2) }}</td>
                </tr>
            </tfoot>
        </table>

        <!-- Footer Section -->
        <div class="footer">
            <!-- Approval Section -->
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <!-- Sales Manager Section -->
                <div style="text-align: right;">
                    <p>___________________________</p>
                    <p style="margin-top: 5px; margin-right: 20px;">Sales Manager</p>
                </div>
            </div>
            <!-- Generated Date -->
            <p style="text-align: center; margin-top: 20px;">Generated on {{ now()->toDayDateTimeString() }}</p>
        </div>
    </div>
</body>

</html>
